bar/urls.py
from django.conf.urls import url
from . import views
from django.urls import path
from django.views.generic import TemplateView

from .views import AddIngredientView, ScanBarCodeView, ScanView, RecognizeView, IngredientAddedView
app_name = 'bar'
urlpatterns = [
    path('', ScanView.as_view(), name='ScanItem'),
    path('decode/', ScanBarCodeView.as_view() ,name='decodeAjax'),
    path('recognize/', RecognizeView.as_view() ,name='recognizeAjax'),
    path('add_ingredient/',  AddIngredientView.as_view(), name="add_ingredient"),
    path('add_new_ingr/', IngredientAddedView.as_view(), name="add_new_ingr"),

]

mnjammnjam/urls.py
from django.contrib import admin
from django.urls import include, path

from base.views import home_view

urlpatterns = [
    path('', home_view),
    path('swiper/', include('swiper.urls')),
    path('base/', include('base.urls')),
    path('admin/', admin.site.urls),
    path('scan_item/',include('bar.urls')),
    path('recognize_image/',include('recognizer.urls')),
]

plugins/card_swiper/urls.py
from django.contrib import admin
from django.urls import include, path

from .views import CardSwipeView, CardListView, CardCreateView

app_name = 'card_swiper'
urlpatterns = [
    path('', CardListView.as_view(), name='card-list'),
    path('swipe/', CardSwipeView.as_view(), name='card-swipe'),
    path('list/', CardListView.as_view(), name='card-list'),
    path('create/', CardCreateView.as_view(), name='card-create'),
    #path('', network_list_view, name='network-list'),
	path('<int:pk>', CardSwipeView.as_view(), name='card-detail'),
    path('admin/', admin.site.urls),
]

bar/models.py
from django.db import models

# Create your models here.
class AddableIngredient(models.Model):
    name = models.CharField(max_length=100, null=False, blank=False)
    nutritions = models.CharField(max_length=1000, null=False, blank=False)
    image_src =models.CharField(max_length=1000, null=False, blank=False)
   

bar/views.py
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.core import serializers
from django.core.files.storage import FileSystemStorage
from django.conf import settings
from django.contrib import messages
from django.contrib.messages import get_messages

from django.views.generic import View
from django.utils.decorators import method_decorator
from . import barCode

from base.models import Ingredient

from .models import AddableIngredient
import json
import requests
# Create your views here.
import ipdb

import base64


@method_decorator(csrf_exempt, name='dispatch')
class ScanView(View):
    template_name = "ScanItem.html" # DetailView

    def get(self, request, id=None, *args, **kwargs):
        # GET method
        return render(request, self.template_name)

@method_decorator(csrf_exempt, name='dispatch')
class ScanBarCodeView(View):
    template_name = "ScanItem.html" # DetailView
    endpoint_url =  'https://eatfit-service.foodcoa.ch/products/{barcode_id}'

    # def get(self, request, id=None, *args, **kwargs):
    #     # GET method
    #     return render(request, self.template_name)


    def post(self, request, id=None,  *args, **kwargs):
        decodedData = barCode.decode(request.POST['imgBase64'])
        if decodedData:

            json_data = json.dumps(decodedData)
            #print(json_data)
            # TODO hard code we only use the first code found
            # 
            item_data = json.loads(json_data)[0]
      
            if item_data["type"] != 'QRCODE':
                result = {}
                url = self.endpoint_url.format(barcode_id=item_data["code"])
                response = requests.get(url , auth=(settings.CSS_BARCODE_APP_ID, settings.CSS_BARCODE_APP_KEY))

                if response.status_code == 200:  # SUCCESS
                    result = response.json()
                    #obj_result = json.loads(result)
                    prod_name = result['products'][0]['product_name_en']

                    prod_nutritions = []
                    for nutr in result['products'][0]['nutrients']:
                        prod_nutritions.append([nutr['name'], str(nutr['amount']) + " " + nutr['unit_of_measure']])
                    prod_image = result['products'][0]['image']
                   
                    result['success'] = True
                    json_nutritions = json.dumps(prod_nutritions, sort_keys=True)
                    ad_in = AddableIngredient(name = prod_name, nutritions = json_nutritions, image_src = prod_image)
                    ad_in.save()
                    return JsonResponse({"code" : 'next'})
                else:
                    result['success'] = False
                    if response.status_code == 404:  # NOT FOUND
                        result['message'] = 'No entry found for "%s"' % word
                    else:
                        result['message'] = 'The Barcode API is not available at the moment. Please try again later.'

            return JsonResponse(result,safe=False)

        return JsonResponse({"code" : 'NO BarCode Found'})


@method_decorator(csrf_exempt, name='dispatch')
class RecognizeView(View):
    api_key = "b1fab0da4af475bbe23771ac4e83e07e55501157"
    food_recognition_url = "https://api-beta.bite.ai/vision/"

    def post(self, request, id=None,  *args, **kwargs):
        decodedData = barCode.recognize(request.POST['imgBase64'])
        if decodedData:

            headers = {'Content-Type': 'application/json',
            'Authorization': 'Bearer {0}'.format(self.api_key)}

            img_base64 = base64.b64encode(decodedData.read())
            img_base64 = img_base64.decode("utf-8")
            
            data = {
                "base64": img_base64
            }
        
            with open('.tmp_img.jpg', "wb") as img:
            
                img.write(decodedData.read())

                
            response = requests.post(self.food_recognition_url, json=data, headers=headers)
            response = response.json()

            
            prod_nutritions = list(response['items'][0]['item']['nutrition_facts'][0]['nutrition'].items())
            prod_nutritions = json.dumps(prod_nutritions)
            prod_name = response['items'][0]['item']['name']
            prod_image = '.tmp_img.jpg'

            result = {}
                  
            result['success'] = True
            
            ad_in = AddableIngredient(name = prod_name, nutritions = prod_nutritions, image_src = prod_image)
            ad_in.save()
            return JsonResponse({"code" : 'next'})
            

    

class AddIngredientView(View):
    template_name = "bar/add_ingredient.html" # DetailView

    def get(self, request, id=None, *args, **kwargs):
        # GET method
        print("get method")

        ad_in = AddableIngredient.objects.last()
        print(AddableIngredient.objects.all())
        context = {}
        prod_name = ad_in.name
        prod_image = ad_in.image_src
        prod_nutritions = json.loads(ad_in.nutritions)
     
        context = {'product_name': prod_name,
                   'image': prod_image,
                   'nutritions': prod_nutritions,
                   }
        return render(request, self.template_name, context)

    def post(self, request, id=None,  *args, **kwargs):
        # POST method
        pass
    


class IngredientAddedView(View):
    template_name = "bar/ingr_added.html" # DetailView

    def get(self, request, id=None, *args, **kwargs):
        # GET method

        ad_in = AddableIngredient.objects.last()
        print(AddableIngredient.objects.all())
        ing = Ingredient(name = ad_in.name, img_path=ad_in.image_src, nutritions=ad_in.nutritions)
        ing.save()
        return render(request, self.template_name, {})

 
    

bar/templates/bar/add_ingredient.html
{%extends 'base.html' %}

{% load static %}
<style>
 .mycontent-left {
     border-right: 1px dashed #333;
 }
</style>

{% block content %}
    <h1 class="page-title">{{ product_name }}</h1>
    <form action='{% url 'bar:add_new_ingr' %}' method='GET'>
        <button class='btn btn-success btn-add' type='submit'>Add Item</button>
    </form>
    <div class="viewport">
        <div class="container ">
            <div class="row">
                <div class="span6">
                    <div class="mycontent-left">

                        <img class="ing_img" src={{ image }} alt="Item-Image">
                    </div>
                </div>
                <div class="span6">
                    <div class="mycontent-right">

            <!-- Headers received from client. -->
            <div class="table-container headers">
                <h2>Nutritions</h2>
                <table class="header-table  table table-hover ">
                    <thead>
                        <tr>
                            <th scope="col">Nutritions Name</th>
                            <th scope="col">Unit</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for nutrition in nutritions %}
                            <tr>
                                <td class="key-cell">
                                    <span>{{ nutrition.0 }}</span>
                                </td>
                                <td class="value-cell">
                                    <span>{{ nutrition.1 }}</span>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
                    </div>
                </div>
            </div>

        </div>
    </div>


{% endblock %}

bar/templates/bar/ingr_added.html
{%extends 'base.html' %}

{% load static %}


{% block content %}
    <h1 class="page-title">Ingredient Added</h1>
    <img src="http://clipart-library.com/newhp/5-52365_cat-face-clipart-png.png" alt="img" />
{% endblock %}